<?php
    /**
     * @author    Blue Acorn iCi <code@blueacornici.com>
     * @copyright Walmart Commerce Technologies. All Rights Reserved.
     */
?>
<?php
    /** @var \Magento\Sales\Block\Order\Email\Items\DefaultItems $block */

    $_item = $block->getItem();

    /** @var \Magento\Sales\Model\Order $_order */
    $_order = $_item->getOrder();
?>

<?= /* @noEscape */ $_order->formatPrice($_item->getTotalPickedDispensedOrCanceled()) ?>
