<?php
/**
 * @author    Blue Acorn iCi <code@blueacornici.com>
 * @copyright Walmart Commerce Technologies. All Rights Reserved.
 *
 * @var $block \Walmart\BopisApiConnector\Block\System\Config\Form\Field\TestConnectionBtn
 * @var $escaper \Magento\Framework\Escaper
 */
?>

<?= $block->getButtonHtml() ?>

<div class="message message-error walmart-api-button-messages hidden" id="walmart-api-test-error-button-msg"></div>

<div class="message message-success walmart-api-button-messages hidden" id="walmart-api-test-success-button-msg"></div>

<script type="text/x-magento-init">
    {
        "*": {
            "Walmart_BopisApiConnector/js/test-connection" : {
                "endPointTestConnection": "<?= $escaper->escapeHtml($block->getEndPointTestConnection()) ?>"
            }
        }
    }
</script>
