<?php
/**
 * @author    Blue Acorn iCi <code@blueacornici.com>
 * @copyright Walmart Commerce Technologies. All Rights Reserved.
 *
 * @var $block \Magento\Framework\View\Element\Template
 * @var $escaper \Magento\Framework\Escaper
 */

/** @var \Magento\Framework\View\Element\Template $block */

/** @var \Walmart\BopisPreferredLocationFrontend\ViewModel\BopisLocationSelection $viewModel */
$viewModel = $block->getData('view_model');
?>

<script async defer src="https://maps.googleapis.com/maps/api/js?key=<?= $viewModel->getGoogleMapsKey() ?>"></script>
