<?php
/**
 * @author    Blue Acorn iCi <code@blueacornici.com>
 * @copyright Walmart Commerce Technologies. All Rights Reserved.
 *
 * @var $block \Magento\Framework\View\Element\Template
 * @var $escaper \Magento\Framework\Escaper
 */

/** @var \Magento\Framework\View\Element\Template $block */
?>
<script type="application/javascript">
    require([], function () {
        'use strict';
        window.checkoutConfig = window.checkoutConfig || {};
    });
</script>
