<?php
/**
 * @author    Blue Acorn iCi <code@blueacornici.com>
 * @copyright Walmart Commerce Technologies. All Rights Reserved.
 */
/**
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 * @var \Magento\User\Block\Buttons $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<form action="<?= $escaper->escapeUrl($block->getUrl('*/*/save')) ?>" method="post" id="role-edit-form">
    <?= $block->getBlockHtml('formkey') ?>
</form>
<?php $scriptString = <<<script

require([
    "jquery",
    "mage/mage"
], function(jQuery){

    jQuery(document).ready(function() {
        jQuery('#role-edit-form').mage('form').mage('validation');
    });

});

script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
