<?php
/**
 * @author    Blue Acorn iCi <code@blueacornici.com>
 * @copyright Walmart Commerce Technologies. All Rights Reserved.
 */

/**
 * @var \Magento\Backend\Block\Template $block
 */

/** @var \Walmart\BopisAlternatePickupContactAdminUi\ViewModel\PickupContact $viewModel */
$viewModel = $block->getData('view_model');
$pickupContact = $viewModel->getPickupContact()
?>
<?php if ($pickupContact): ?>
    <section class="admin__page-section order-addresses">
        <div class="admin__page-section-title">
            <span class="title"><?= $block->escapeHtml(__('Alternate Pickup Contact')) ?></span>
        </div>
        <div class="admin__page-section-content">
            <div class="admin__page-section-item order-pickup-contact">
                <div class="admin__page-section-item-title">
                    <span class="title"><?= $block->escapeHtml(__('Pickup Contact')) ?></span>
                </div>
                <address class="admin__page-section-item-content">
                    <p>
                        <?= $block->escapeHtml($pickupContact->getFirstname()) ?>
                        <?= $block->escapeHtml($pickupContact->getLastname()) ?>
                    </p>
                    <p><?= $block->escapeHtml($pickupContact->getTelephone()) ?></p>
                    <p><?= $block->escapeHtml($pickupContact->getEmail()) ?></p>
                </address>
            </div>
        </div>
    </section>
<?php endif ?>
